SHELL := /bin/bash

all: Readme.md

Readme.md: xattr-edit.py requirements.txt Readme.md.template
	{ \
		. ~/.virtualenvs/$$(cat .venv)/bin/activate ; \
		echo "THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT. EDIT Readme.md.template INSTEAD!" ;\
		eval "$$(cat Readme.md.template)" ;\
	} >$@

